---
title: "Week1 | Rによる自主勉強会"
author: "伊﨑 直志"
date: '2023年10月6日'
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
---
## 準備
### Loading Packages
libraryで使用する関数の読み込み
```{r setup, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)
```

- `tidyverse`：データ処理および可視化（今回は特に使わない）

## A.3　Rの基本操作
### A.3.1　数式の入力
Rの基本操作

- 足し算: +
- 引き算: -
- 掛け算: *
- 割り算: /

```{r}
1+1
2+3*4; (2+3)*4 #複数の式を１行で実行　セミコロン「;」, べき乗「^」
5^2
```

変数への代入（Environment>Valuesで確認）
- [文字]<-[数字]

```{r}
A <- 6-1
A; A^2
B <- c(6,7,8) #複数要素の格納, c(a,b,c...)→各要素それぞれ計算
(B-1)/2
```

### A.3.2　スクリプトの利用
### A.3.3　データの読み込み, 基礎統計の計算
- read.csv("data.csv")    or
- read.csv("[ファイルパス]/data.csv")   or
- setwd("[ファイルパス]") %>% read.csv("data.csv")
```{r}
read.csv("data.csv") #オブジェクトへの格納→Environmentにて確認
df <- read.csv("data.csv")
head(df) #中身の確認
```
- 平均: mean()
- 標準偏差: sd()　#standard deviation
- 最小値: min()
- 最大値: max()

[参考](https://ai-trend.jp/programming/r-beginner/r-2/)

```{r}
mean(df$age); sd(df$age); min(df$age); max(df$age) #$: 一つの項目だけ取り出す
```

### A.3.4　パッケージのインストール
- 右下区画のタブ>Packages>Install
- Command: install.packages("[パッケージ名]")
→例略